modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/cech12/CeramicBucket/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="ceramicbucket"
    version="${file.jarVersion}"
    displayName="Ceramic Bucket"
    displayURL="https://github.com/cech12/CeramicBucket"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Ceramic Bucket.
    '''
[[dependencies.ceramicbucket]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramicbucket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramicbucket]]
    modId="bucketlib"
    mandatory=true
    versionRange="[1.18.2-0.5.1.0,)"
    ordering="NONE"
    side="BOTH"