modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/cech12/CeramicBucket/issues"
license="The MIT License (MIT)"
[[mods]]
    modId="ceramicbucket"
    version="${file.jarVersion}"
    displayName="Ceramic Bucket"
    displayURL="https://github.com/cech12/CeramicBucket"
    logoFile="logo.png"
    authors="Cech12"
    description='''
    A mod which adds a Ceramic Bucket.
    '''
[[dependencies.ceramicbucket]]
    modId="forge"
    mandatory=true
    versionRange="[28.2.11,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramicbucket]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ceramicbucket]]
   modId="jei"
   mandatory=false
   versionRange="[6.0.0.27,)"
   ordering="NONE"
   side="BOTH"